import { useState } from "react";

export default function ExamPrepPage({ onBack }) {
  const [activeTab, setActiveTab] = useState("overview");

  const examTypes = [
    {
      name: "SSC Exams",
      icon: "🏛️",
      description: "Staff Selection Commission",
      exams: ["SSC CGL", "SSC CHSL", "SSC MTS", "SSC GD"],
      subjects: [
        "General Awareness",
        "Reasoning",
        "Quantitative Aptitude",
        "English",
      ],
    },
    {
      name: "Banking Exams",
      icon: "🏦",
      description: "Banking Sector Recruitment",
      exams: ["IBPS PO", "IBPS Clerk", "SBI PO", "RBI Grade B"],
      subjects: [
        "Banking Awareness",
        "Current Affairs",
        "Reasoning",
        "Quantitative Aptitude",
      ],
    },
    {
      name: "Railway Exams",
      icon: "🚂",
      description: "Railway Recruitment Board",
      exams: ["RRB NTPC", "RRB JE", "RRB Group D", "RRB ALP"],
      subjects: [
        "General Awareness",
        "Mathematics",
        "General Intelligence",
        "General Science",
      ],
    },
    {
      name: "Defense Exams",
      icon: "🛡️",
      description: "Defense Services",
      exams: ["NDA", "CDS", "AFCAT", "Indian Navy"],
      subjects: [
        "General Knowledge",
        "Mathematics",
        "English",
        "Current Affairs",
      ],
    },
  ];

  const features = [
    {
      icon: "🤖",
      title: "AI-Powered Questions",
      description:
        "Get unlimited practice questions generated by advanced AI, tailored to your exam pattern and difficulty level.",
    },
    {
      icon: "📊",
      title: "Adaptive Difficulty",
      description:
        "Questions adapt to your performance level - start easy and gradually increase difficulty as you improve.",
    },
    {
      icon: "⏱️",
      title: "Timed Practice",
      description:
        "Practice with realistic time constraints to build speed and accuracy for actual exam conditions.",
    },
    {
      icon: "📈",
      title: "Performance Analytics",
      description:
        "Track your progress with detailed analytics showing strengths, weaknesses, and improvement areas.",
    },
    {
      icon: "🎯",
      title: "Subject-wise Practice",
      description:
        "Focus on specific subjects like Current Affairs, Reasoning, Quantitative Aptitude, and General Knowledge.",
    },
    {
      icon: "💡",
      title: "Instant Explanations",
      description:
        "Get detailed explanations for every answer to understand concepts and learn from mistakes.",
    },
  ];

  const studyPlan = [
    {
      phase: "Foundation",
      duration: "Week 1-2",
      focus: "Basic concepts and easy questions",
      activities: [
        "Start with easy difficulty",
        "Focus on one subject at a time",
        "Build confidence with shorter quizzes",
      ],
    },
    {
      phase: "Building",
      duration: "Week 3-6",
      focus: "Medium difficulty and mixed subjects",
      activities: [
        "Increase to medium difficulty",
        "Mix different subjects",
        "Extend quiz duration",
      ],
    },
    {
      phase: "Mastery",
      duration: "Week 7-10",
      focus: "Hard questions and exam simulation",
      activities: [
        "Practice hard difficulty questions",
        "Full-length mock tests",
        "Time management practice",
      ],
    },
    {
      phase: "Revision",
      duration: "Final 2 weeks",
      focus: "Quick revision and weak areas",
      activities: [
        "Focus on weak subjects",
        "Quick daily practice",
        "Last-minute current affairs",
      ],
    },
  ];

  return (
    <div className="exam-prep-page">
      {/* Header */}
      <div className="glass-card exam-prep-header">
        <button onClick={onBack} className="back-btn">
          ← Back to Practice
        </button>
        <div className="header-content">
          <h1 className="page-title">
            Master <span className="gradient-text">Government Exams</span>
          </h1>
          <p className="page-subtitle">
            Your AI-powered companion for SSC, Banking, Railway, and Defense
            exam preparation
          </p>
        </div>
      </div>

      {/* Navigation Tabs */}
      <div className="glass-card tab-navigation">
        <div className="tab-buttons">
          {[
            { id: "overview", label: "Overview", icon: "📋" },
            { id: "exams", label: "Supported Exams", icon: "📚" },
            { id: "features", label: "Features", icon: "⭐" },
            { id: "study-plan", label: "Study Plan", icon: "📅" },
          ].map((tab) => (
            <button
              key={tab.id}
              onClick={() => setActiveTab(tab.id)}
              className={`tab-btn ${activeTab === tab.id ? "active" : ""}`}
            >
              <span className="tab-icon">{tab.icon}</span>
              <span className="tab-label">{tab.label}</span>
            </button>
          ))}
        </div>
      </div>

      {/* Tab Content */}
      <div className="tab-content">
        {activeTab === "overview" && (
          <div className="overview-section">
            <div className="glass-card overview-card">
              <h2 className="section-title">Why Choose Inquizzitive?</h2>
              <div className="overview-grid">
                <div className="overview-item">
                  <div className="overview-icon">🎯</div>
                  <h3>Targeted Practice</h3>
                  <p>
                    Practice questions specifically designed for government exam
                    patterns with real exam-like difficulty levels.
                  </p>
                </div>
                <div className="overview-item">
                  <div className="overview-icon">🔄</div>
                  <h3>Unlimited Questions</h3>
                  <p>
                    Never run out of practice material. Our AI generates fresh
                    questions every time you practice.
                  </p>
                </div>
                <div className="overview-item">
                  <div className="overview-icon">📱</div>
                  <h3>Practice Anywhere</h3>
                  <p>
                    Study on-the-go with our responsive design that works
                    perfectly on all devices.
                  </p>
                </div>
                <div className="overview-item">
                  <div className="overview-icon">🏆</div>
                  <h3>Exam Success</h3>
                  <p>
                    Build confidence and improve scores with systematic practice
                    and detailed performance feedback.
                  </p>
                </div>
              </div>
            </div>

            <div className="glass-card success-stats">
              <h3 className="stats-title">Success Statistics</h3>
              <div className="stats-grid">
                <div className="stat-item">
                  <div className="stat-number">85%</div>
                  <div className="stat-label">Average Score Improvement</div>
                </div>
                <div className="stat-item">
                  <div className="stat-number">50K+</div>
                  <div className="stat-label">Questions Generated</div>
                </div>
                <div className="stat-item">
                  <div className="stat-number">95%</div>
                  <div className="stat-label">User Satisfaction</div>
                </div>
              </div>
            </div>
          </div>
        )}

        {activeTab === "exams" && (
          <div className="exams-section">
            <div className="glass-card exams-intro">
              <h2 className="section-title">Supported Government Exams</h2>
              <p className="section-description">
                Comprehensive preparation for major government recruitment exams
                across different sectors
              </p>
            </div>

            <div className="exams-grid">
              {examTypes.map((exam, index) => (
                <div key={index} className="glass-card exam-card">
                  <div className="exam-header">
                    <div className="exam-icon">{exam.icon}</div>
                    <div className="exam-info">
                      <h3 className="exam-name">{exam.name}</h3>
                      <p className="exam-description">{exam.description}</p>
                    </div>
                  </div>

                  <div className="exam-details">
                    <div className="exam-list">
                      <h4>Popular Exams:</h4>
                      <ul>
                        {exam.exams.map((examName, idx) => (
                          <li key={idx}>{examName}</li>
                        ))}
                      </ul>
                    </div>

                    <div className="subject-list">
                      <h4>Key Subjects:</h4>
                      <div className="subject-tags">
                        {exam.subjects.map((subject, idx) => (
                          <span key={idx} className="subject-tag">
                            {subject}
                          </span>
                        ))}
                      </div>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}

        {activeTab === "features" && (
          <div className="features-section">
            <div className="glass-card features-intro">
              <h2 className="section-title">
                Powerful Features for Exam Success
              </h2>
              <p className="section-description">
                Advanced tools and features designed to maximize your
                preparation efficiency
              </p>
            </div>

            <div className="features-grid">
              {features.map((feature, index) => (
                <div key={index} className="glass-card feature-card">
                  <div className="feature-icon">{feature.icon}</div>
                  <h3 className="feature-title">{feature.title}</h3>
                  <p className="feature-description">{feature.description}</p>
                </div>
              ))}
            </div>
          </div>
        )}

        {activeTab === "study-plan" && (
          <div className="study-plan-section">
            <div className="glass-card study-plan-intro">
              <h2 className="section-title">12-Week Study Plan</h2>
              <p className="section-description">
                A structured approach to maximize your exam preparation with
                Inquizzitive
              </p>
            </div>

            <div className="study-plan-timeline">
              {studyPlan.map((phase, index) => (
                <div key={index} className="glass-card phase-card">
                  <div className="phase-header">
                    <div className="phase-number">{index + 1}</div>
                    <div className="phase-info">
                      <h3 className="phase-name">{phase.phase} Phase</h3>
                      <p className="phase-duration">{phase.duration}</p>
                    </div>
                  </div>

                  <div className="phase-content">
                    <p className="phase-focus">
                      <strong>Focus:</strong> {phase.focus}
                    </p>
                    <div className="phase-activities">
                      <h4>Key Activities:</h4>
                      <ul>
                        {phase.activities.map((activity, idx) => (
                          <li key={idx}>{activity}</li>
                        ))}
                      </ul>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}
      </div>

      {/* Call to Action */}
      <div className="glass-card cta-section">
        <h2 className="cta-title">Ready to Start Your Journey?</h2>
        <p className="cta-description">
          Join thousands of successful candidates who achieved their government
          job dreams with Inquizzitive
        </p>
        <button onClick={onBack} className="cta-btn">
          <span>🚀</span>
          Start Practicing Now
        </button>
      </div>
    </div>
  );
}
